#!/usr/bin/env bash
# Regenerates docs/schema.sql: applies every migration to a throwaway local D1 and dumps the resulting schema.
# Reference only. Schema changes still go in a new migrations/*.sql file.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_PATH="$ROOT_DIR/docs/schema.sql"
STATE_DIR="$(mktemp -d)"
trap 'rm -rf "$STATE_DIR"' EXIT

cd "$ROOT_DIR"
npx wrangler d1 migrations apply DB --local --persist-to "$STATE_DIR" > /dev/null
npx wrangler d1 execute DB --local --persist-to "$STATE_DIR" --json --command \
  "SELECT sql FROM sqlite_master
   WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '_cf_%' AND name != 'd1_migrations'
   ORDER BY tbl_name, type != 'table', name" \
  | node -e '
      const rows = JSON.parse(require("node:fs").readFileSync(0, "utf8"))[0].results;
      const header = [
        "-- Current database schema: the result of applying every file in migrations/ in order.",
        "-- Generated by scripts/dump-schema.sh (npm run schema:dump). Do not edit or apply this file;",
        "-- add a new migration instead and regenerate.",
        ""
      ];
      const statements = rows.map((row) => (row.sql.startsWith("CREATE TABLE") ? "\n" : "") + row.sql + ";");
      process.stdout.write(header.concat(statements).join("\n").replace(/\n{3,}/g, "\n\n") + "\n");
    ' > "$OUT_PATH"

echo "Wrote $OUT_PATH"
