-- Current database schema: the result of applying every file in migrations/ in order.
-- Generated by scripts/dump-schema.sh (npm run schema:dump). Do not edit or apply this file;
-- add a new migration instead and regenerate.

CREATE TABLE announcement_queue (
  game_id TEXT PRIMARY KEY,
  queued_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);

CREATE TABLE anonymous_favorites (
  anon_id TEXT NOT NULL,
  game_id TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (anon_id, game_id),
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);
CREATE INDEX idx_anonymous_favorites_game ON anonymous_favorites(game_id);

CREATE TABLE anonymous_votes (
  anon_ip_hash TEXT NOT NULL,
  game_id TEXT NOT NULL,
  value INTEGER NOT NULL CHECK (value IN (-1, 1)),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (anon_ip_hash, game_id),
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);
CREATE INDEX idx_anonymous_votes_game ON anonymous_votes(game_id);

CREATE TABLE audit_log (
  id TEXT PRIMARY KEY,
  actor_user_id TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  action TEXT NOT NULL,
  metadata_json TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (actor_user_id) REFERENCES users(id)
);

CREATE TABLE categories (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_by_user_id TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (created_by_user_id) REFERENCES users(id)
);

CREATE TABLE curated_list_items (
  curated_list_id TEXT NOT NULL,
  game_id TEXT NOT NULL,
  position INTEGER NOT NULL,
  added_by_user_id TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (curated_list_id, game_id),
  FOREIGN KEY (curated_list_id) REFERENCES curated_lists(id) ON DELETE CASCADE,
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  FOREIGN KEY (added_by_user_id) REFERENCES users(id)
);
CREATE UNIQUE INDEX idx_curated_list_position ON curated_list_items(curated_list_id, position);

CREATE TABLE curated_lists (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT,
  visibility TEXT NOT NULL DEFAULT 'private' CHECK (visibility IN ('public', 'private')),
  owner_user_id TEXT NOT NULL,
  created_by_user_id TEXT NOT NULL,
  updated_by_user_id TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')), twitch_login TEXT, twitch_user_id TEXT,
  FOREIGN KEY (owner_user_id) REFERENCES users(id),
  FOREIGN KEY (created_by_user_id) REFERENCES users(id),
  FOREIGN KEY (updated_by_user_id) REFERENCES users(id)
);

CREATE TABLE favorites (
  user_id TEXT NOT NULL,
  game_id TEXT NOT NULL,
  position INTEGER NOT NULL,
  weekday_mask INTEGER NOT NULL DEFAULT 127,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (user_id, game_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX idx_favorites_user_position ON favorites(user_id, position);

CREATE TABLE game_categories (
  game_id TEXT NOT NULL,
  category_id TEXT NOT NULL,
  assigned_by_user_id TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (game_id, category_id),
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
  FOREIGN KEY (assigned_by_user_id) REFERENCES users(id)
);
CREATE INDEX idx_game_categories_category ON game_categories(category_id, game_id);

CREATE TABLE games (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  url TEXT NOT NULL,
  canonical_url TEXT NOT NULL UNIQUE,
  description TEXT,
  source_name TEXT,
  source_url TEXT,
  submitted_by_user_id TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'disabled')),
  moderation_note TEXT,
  score REAL NOT NULL DEFAULT 0,
  vote_up_count INTEGER NOT NULL DEFAULT 0,
  vote_down_count INTEGER NOT NULL DEFAULT 0,
  report_count INTEGER NOT NULL DEFAULT 0,
  link_fail_count INTEGER NOT NULL DEFAULT 0,
  last_checked_at TEXT,
  approved_at TEXT,
  approved_by_user_id TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  reset_basis TEXT CHECK (reset_basis IN ('local', 'server')),
  reset_time_minutes INTEGER CHECK (reset_time_minutes >= 0 AND reset_time_minutes <= 1439),
  click_count INTEGER NOT NULL DEFAULT 0,
  paywall INTEGER NOT NULL DEFAULT 0, nsfw INTEGER NOT NULL DEFAULT 0, reset_timezone TEXT, how_to_play TEXT,
  FOREIGN KEY (submitted_by_user_id) REFERENCES users(id),
  FOREIGN KEY (approved_by_user_id) REFERENCES users(id)
);
CREATE INDEX idx_games_status_created ON games(status, created_at DESC);
CREATE INDEX idx_games_status_score ON games(status, score DESC);

CREATE TABLE "oauth_accounts" (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  provider TEXT NOT NULL CHECK (provider IN ('google', 'github', 'discord', 'twitch')),
  provider_user_id TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(provider, provider_user_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE rate_limits (
  key TEXT PRIMARY KEY,
  window_start INTEGER NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_rate_limits_updated_at ON rate_limits(updated_at);

CREATE TABLE reports (
  id TEXT PRIMARY KEY,
  game_id TEXT NOT NULL,
  reported_by_user_id TEXT NOT NULL,
  reason TEXT NOT NULL CHECK (reason IN ('broken', 'not_daily', 'spam', 'other')),
  note TEXT,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved', 'dismissed')),
  resolved_by_user_id TEXT,
  resolved_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  FOREIGN KEY (reported_by_user_id) REFERENCES users(id),
  FOREIGN KEY (resolved_by_user_id) REFERENCES users(id)
);
CREATE INDEX idx_reports_status_created ON reports(status, created_at DESC);

CREATE TABLE sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  display_name TEXT,
  avatar_url TEXT,
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'editor', 'admin')),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
, rotation_share_token TEXT DEFAULT NULL);
CREATE UNIQUE INDEX idx_users_rotation_share_token ON users(rotation_share_token) WHERE rotation_share_token IS NOT NULL;

CREATE TABLE votes (
  user_id TEXT NOT NULL,
  game_id TEXT NOT NULL,
  value INTEGER NOT NULL CHECK (value IN (-1, 1)),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (user_id, game_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);
CREATE INDEX idx_votes_game ON votes(game_id);
